# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rknn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Model(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Model()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ModelBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x4B\x4E\x4E", size_prefixed=size_prefixed)

    # Model
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Model
    def Var1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Model
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def Graphs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from rknncli.schema.rknn.Graph import Graph
            obj = Graph()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def GraphsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def GraphsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Model
    def Generator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def Var2(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from rknncli.schema.rknn.Type1 import Type1
            obj = Type1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def Var2Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def Var2IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Model
    def Var3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Model
    def Var4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Model
    def Compiler(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def Runtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def Var5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Model
    def Var6(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Model
    def InputJson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model
    def OutputJson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ModelStart(builder):
    builder.StartObject(14)

def Start(builder):
    ModelStart(builder)

def ModelAddVar1(builder, var1):
    builder.PrependInt32Slot(0, var1, 0)

def AddVar1(builder, var1):
    ModelAddVar1(builder, var1)

def ModelAddFormat(builder, format):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(format), 0)

def AddFormat(builder, format):
    ModelAddFormat(builder, format)

def ModelAddGraphs(builder, graphs):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(graphs), 0)

def AddGraphs(builder, graphs):
    ModelAddGraphs(builder, graphs)

def ModelStartGraphsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGraphsVector(builder, numElems):
    return ModelStartGraphsVector(builder, numElems)

def ModelAddGenerator(builder, generator):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(generator), 0)

def AddGenerator(builder, generator):
    ModelAddGenerator(builder, generator)

def ModelAddVar2(builder, var2):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(var2), 0)

def AddVar2(builder, var2):
    ModelAddVar2(builder, var2)

def ModelStartVar2Vector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVar2Vector(builder, numElems):
    return ModelStartVar2Vector(builder, numElems)

def ModelAddVar3(builder, var3):
    builder.PrependInt32Slot(5, var3, 0)

def AddVar3(builder, var3):
    ModelAddVar3(builder, var3)

def ModelAddVar4(builder, var4):
    builder.PrependInt32Slot(6, var4, 0)

def AddVar4(builder, var4):
    ModelAddVar4(builder, var4)

def ModelAddCompiler(builder, compiler):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(compiler), 0)

def AddCompiler(builder, compiler):
    ModelAddCompiler(builder, compiler)

def ModelAddRuntime(builder, runtime):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(runtime), 0)

def AddRuntime(builder, runtime):
    ModelAddRuntime(builder, runtime)

def ModelAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    ModelAddSource(builder, source)

def ModelAddVar5(builder, var5):
    builder.PrependBoolSlot(10, var5, 0)

def AddVar5(builder, var5):
    ModelAddVar5(builder, var5)

def ModelAddVar6(builder, var6):
    builder.PrependInt32Slot(11, var6, 0)

def AddVar6(builder, var6):
    ModelAddVar6(builder, var6)

def ModelAddInputJson(builder, inputJson):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(inputJson), 0)

def AddInputJson(builder, inputJson):
    ModelAddInputJson(builder, inputJson)

def ModelAddOutputJson(builder, outputJson):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(outputJson), 0)

def AddOutputJson(builder, outputJson):
    ModelAddOutputJson(builder, outputJson)

def ModelEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelEnd(builder)

import rknncli.schema.rknn.Graph
import rknncli.schema.rknn.Type1
try:
    from typing import List
except:
    pass

class ModelT(object):

    # ModelT
    def __init__(
        self,
        var1 = 0,
        format = None,
        graphs = None,
        generator = None,
        var2 = None,
        var3 = 0,
        var4 = 0,
        compiler = None,
        runtime = None,
        source = None,
        var5 = False,
        var6 = 0,
        inputJson = None,
        outputJson = None,
    ):
        self.var1 = var1  # type: int
        self.format = format  # type: Optional[str]
        self.graphs = graphs  # type: Optional[List[rknn.Graph.GraphT]]
        self.generator = generator  # type: Optional[str]
        self.var2 = var2  # type: Optional[List[rknn.Type1.Type1T]]
        self.var3 = var3  # type: int
        self.var4 = var4  # type: int
        self.compiler = compiler  # type: Optional[str]
        self.runtime = runtime  # type: Optional[str]
        self.source = source  # type: Optional[str]
        self.var5 = var5  # type: bool
        self.var6 = var6  # type: int
        self.inputJson = inputJson  # type: Optional[str]
        self.outputJson = outputJson  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        model = Model()
        model.Init(buf, pos)
        return cls.InitFromObj(model)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, model):
        x = ModelT()
        x._UnPack(model)
        return x

    # ModelT
    def _UnPack(self, model):
        if model is None:
            return
        self.var1 = model.Var1()
        self.format = model.Format()
        if not model.GraphsIsNone():
            self.graphs = []
            for i in range(model.GraphsLength()):
                if model.Graphs(i) is None:
                    self.graphs.append(None)
                else:
                    graph_ = rknn.Graph.GraphT.InitFromObj(model.Graphs(i))
                    self.graphs.append(graph_)
        self.generator = model.Generator()
        if not model.Var2IsNone():
            self.var2 = []
            for i in range(model.Var2Length()):
                if model.Var2(i) is None:
                    self.var2.append(None)
                else:
                    type1_ = rknn.Type1.Type1T.InitFromObj(model.Var2(i))
                    self.var2.append(type1_)
        self.var3 = model.Var3()
        self.var4 = model.Var4()
        self.compiler = model.Compiler()
        self.runtime = model.Runtime()
        self.source = model.Source()
        self.var5 = model.Var5()
        self.var6 = model.Var6()
        self.inputJson = model.InputJson()
        self.outputJson = model.OutputJson()

    # ModelT
    def Pack(self, builder):
        if self.format is not None:
            format = builder.CreateString(self.format)
        if self.graphs is not None:
            graphslist = []
            for i in range(len(self.graphs)):
                graphslist.append(self.graphs[i].Pack(builder))
            ModelStartGraphsVector(builder, len(self.graphs))
            for i in reversed(range(len(self.graphs))):
                builder.PrependUOffsetTRelative(graphslist[i])
            graphs = builder.EndVector()
        if self.generator is not None:
            generator = builder.CreateString(self.generator)
        if self.var2 is not None:
            var2list = []
            for i in range(len(self.var2)):
                var2list.append(self.var2[i].Pack(builder))
            ModelStartVar2Vector(builder, len(self.var2))
            for i in reversed(range(len(self.var2))):
                builder.PrependUOffsetTRelative(var2list[i])
            var2 = builder.EndVector()
        if self.compiler is not None:
            compiler = builder.CreateString(self.compiler)
        if self.runtime is not None:
            runtime = builder.CreateString(self.runtime)
        if self.source is not None:
            source = builder.CreateString(self.source)
        if self.inputJson is not None:
            inputJson = builder.CreateString(self.inputJson)
        if self.outputJson is not None:
            outputJson = builder.CreateString(self.outputJson)
        ModelStart(builder)
        ModelAddVar1(builder, self.var1)
        if self.format is not None:
            ModelAddFormat(builder, format)
        if self.graphs is not None:
            ModelAddGraphs(builder, graphs)
        if self.generator is not None:
            ModelAddGenerator(builder, generator)
        if self.var2 is not None:
            ModelAddVar2(builder, var2)
        ModelAddVar3(builder, self.var3)
        ModelAddVar4(builder, self.var4)
        if self.compiler is not None:
            ModelAddCompiler(builder, compiler)
        if self.runtime is not None:
            ModelAddRuntime(builder, runtime)
        if self.source is not None:
            ModelAddSource(builder, source)
        ModelAddVar5(builder, self.var5)
        ModelAddVar6(builder, self.var6)
        if self.inputJson is not None:
            ModelAddInputJson(builder, inputJson)
        if self.outputJson is not None:
            ModelAddOutputJson(builder, outputJson)
        model = ModelEnd(builder)
        return model
