# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rknn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Type3(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Type3()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsType3(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Type3BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x4B\x4E\x4E", size_prefixed=size_prefixed)

    # Type3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Type3
    def Var1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Type3Start(builder):
    builder.StartObject(1)

def Start(builder):
    Type3Start(builder)

def Type3AddVar1(builder, var1):
    builder.PrependInt32Slot(0, var1, 0)

def AddVar1(builder, var1):
    Type3AddVar1(builder, var1)

def Type3End(builder):
    return builder.EndObject()

def End(builder):
    return Type3End(builder)
