# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rknn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Type2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Type2()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsType2(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Type2BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x4B\x4E\x4E", size_prefixed=size_prefixed)

    # Type2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Type2
    def Var1(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Type2
    def Var1AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Type2
    def Var1Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Type2
    def Var1IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Type2
    def Var2(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Type2
    def Var2AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Type2
    def Var2Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Type2
    def Var2IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Type2
    def Var3(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Type2
    def Var3AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Type2
    def Var3Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Type2
    def Var3IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def Type2Start(builder):
    builder.StartObject(3)

def Start(builder):
    Type2Start(builder)

def Type2AddVar1(builder, var1):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(var1), 0)

def AddVar1(builder, var1):
    Type2AddVar1(builder, var1)

def Type2StartVar1Vector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVar1Vector(builder, numElems):
    return Type2StartVar1Vector(builder, numElems)

def Type2AddVar2(builder, var2):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(var2), 0)

def AddVar2(builder, var2):
    Type2AddVar2(builder, var2)

def Type2StartVar2Vector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVar2Vector(builder, numElems):
    return Type2StartVar2Vector(builder, numElems)

def Type2AddVar3(builder, var3):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(var3), 0)

def AddVar3(builder, var3):
    Type2AddVar3(builder, var3)

def Type2StartVar3Vector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVar3Vector(builder, numElems):
    return Type2StartVar3Vector(builder, numElems)

def Type2End(builder):
    return builder.EndObject()

def End(builder):
    return Type2End(builder)

try:
    from typing import List
except:
    pass

class Type2T(object):

    # Type2T
    def __init__(
        self,
        var1 = None,
        var2 = None,
        var3 = None,
    ):
        self.var1 = var1  # type: Optional[List[int]]
        self.var2 = var2  # type: Optional[List[int]]
        self.var3 = var3  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        type2 = Type2()
        type2.Init(buf, pos)
        return cls.InitFromObj(type2)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, type2):
        x = Type2T()
        x._UnPack(type2)
        return x

    # Type2T
    def _UnPack(self, type2):
        if type2 is None:
            return
        if not type2.Var1IsNone():
            if np is None:
                self.var1 = []
                for i in range(type2.Var1Length()):
                    self.var1.append(type2.Var1(i))
            else:
                self.var1 = type2.Var1AsNumpy()
        if not type2.Var2IsNone():
            if np is None:
                self.var2 = []
                for i in range(type2.Var2Length()):
                    self.var2.append(type2.Var2(i))
            else:
                self.var2 = type2.Var2AsNumpy()
        if not type2.Var3IsNone():
            if np is None:
                self.var3 = []
                for i in range(type2.Var3Length()):
                    self.var3.append(type2.Var3(i))
            else:
                self.var3 = type2.Var3AsNumpy()

    # Type2T
    def Pack(self, builder):
        if self.var1 is not None:
            if np is not None and type(self.var1) is np.ndarray:
                var1 = builder.CreateNumpyVector(self.var1)
            else:
                Type2StartVar1Vector(builder, len(self.var1))
                for i in reversed(range(len(self.var1))):
                    builder.PrependInt32(self.var1[i])
                var1 = builder.EndVector()
        if self.var2 is not None:
            if np is not None and type(self.var2) is np.ndarray:
                var2 = builder.CreateNumpyVector(self.var2)
            else:
                Type2StartVar2Vector(builder, len(self.var2))
                for i in reversed(range(len(self.var2))):
                    builder.PrependInt32(self.var2[i])
                var2 = builder.EndVector()
        if self.var3 is not None:
            if np is not None and type(self.var3) is np.ndarray:
                var3 = builder.CreateNumpyVector(self.var3)
            else:
                Type2StartVar3Vector(builder, len(self.var3))
                for i in reversed(range(len(self.var3))):
                    builder.PrependInt32(self.var3[i])
                var3 = builder.EndVector()
        Type2Start(builder)
        if self.var1 is not None:
            Type2AddVar1(builder, var1)
        if self.var2 is not None:
            Type2AddVar2(builder, var2)
        if self.var3 is not None:
            Type2AddVar3(builder, var3)
        type2 = Type2End(builder)
        return type2
