# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rknn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Type1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Type1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsType1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Type1BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x4B\x4E\x4E", size_prefixed=size_prefixed)

    # Type1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Type1
    def Var1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Type1Start(builder):
    builder.StartObject(1)

def Start(builder):
    Type1Start(builder)

def Type1AddVar1(builder, var1):
    builder.PrependInt32Slot(0, var1, 0)

def AddVar1(builder, var1):
    Type1AddVar1(builder, var1)

def Type1End(builder):
    return builder.EndObject()

def End(builder):
    return Type1End(builder)


class Type1T(object):

    # Type1T
    def __init__(
        self,
        var1 = 0,
    ):
        self.var1 = var1  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        type1 = Type1()
        type1.Init(buf, pos)
        return cls.InitFromObj(type1)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, type1):
        x = Type1T()
        x._UnPack(type1)
        return x

    # Type1T
    def _UnPack(self, type1):
        if type1 is None:
            return
        self.var1 = type1.Var1()

    # Type1T
    def Pack(self, builder):
        Type1Start(builder)
        Type1AddVar1(builder, self.var1)
        type1 = Type1End(builder)
        return type1
